GET http://localhost:7432/wimt/api/v1/track
Accept: application/json
Authorization: Bearer 1e69205c

###
POST http://localhost:7432/wimt/api/v1/track
Content-Type: application/json
Authorization: Bearer 1e69205c

[
  {
    "windowName": "test",
    "processName": "test",
    "wastedTime": 123
  }
]

###
POST http://localhost:7433/aus/api/v1/auth
Content-Type: application/json

{
  "username": "testee",
  "password": "testee"
}

###
