version: "3.9"

services:
  wimt:
    build:
      context: ..
      dockerfile: app-dock/Dockerfile
      args:
        SERVICE: whereismytime-service
    container_name: wimt-service
    ports:
      - "7432:7432"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tracked_time_database
    networks:
      - wimtnet

  aus:
    build:
      context: ..
      dockerfile: app-dock/Dockerfile
      args:
        SERVICE: authentication-service
    container_name: aus-service
    ports:
      - "7433:7433"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/authentication_database
    networks:
      - wimtnet

  nginx:
    image: nginx:1.21.1
    container_name: nginx
    volumes:
      - "./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "7430:80"
    depends_on:
      - wimt
      - aus
    networks:
      - wimtnet

networks:
  wimtnet:
    external:
      name: wimt_network
