version: "3.9"
services:
  postgres:
    build:
      context: .
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      - PGDATA=/pgtmpfs
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - wimtnet

networks:
  wimtnet:
    name: wimt_network